version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_nginx_app
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    restart: unless-stopped
